### ISSUE TITLE
0.2.1 release

### ISSUE THREAD

**Issue by pomartel** [yuanqing/autosize-input#1]
Thanks for this very useful plugin! Would it be possible to create a 0.2.1 release so it can be added to https://rails-assets.org/#/components/yuanqing--autosize-input

**Comment by yuanqing** [comment]
@pomartel

Done: https://github.com/yuanqing/autosize-input/releases/tag/v0.2.1

**Comment by pomartel** [comment]
Awesome! Thanks!
