### ISSUE TITLE
destroy method

### ISSUE THREAD

**Issue by bogdancss** [yuanqing/autosize-input#10]
Is it possible to destroy the instance - or a way to reinit it?

**Comment by yuanqing** [comment]
@b0gd4n Reinitialise by calling the function returned by `autosizeInput`:

```js
const foo = autosizeInput(document.querySelector('#foo'))

// ...

foo()
```

**Comment by bogdancss** [comment]
what I am trying to achieve with this is make it responde to screen resizing - I have a breakpoint which makes the font-size for the input smaller for mobile. That means that the initial width calculated by the placeholder will be smaller - so I need to reinit it at that point

`const foo = autosizeInput(document.querySelector('#search'));`

calling `foo()` inside a resize function doesn't fix this.

**Comment by psugihara** [comment]
This would also be useful for removing the ghost element and removing event binding that may turn into memory leaks.

I could implement when I have time, but what would be the preferred API? We could have autosizeInput return an object with multiple functions e.g.:

`return { set, destroy };`

**Comment by yuanqing** [comment]
The module returns a `destroy` method as of `1.0.0`
