### ISSUE TITLE
Cannot Find Module

### ISSUE THREAD

**Issue by dustincleveland** [yuanqing/autosize-input#12]
When I try to use this package with TypeScript/Webpack/Angular 2 I receive this error during my build: `TS2307: Cannot find module 'autosize-input'.` Imported like so:

```
import * as autosizeInput from 'autosize-input';
```

It is worth mentioning is that the application does run, it just doesn't compile correctly.

Webpack: 2.2.1
TypeScript: 2.0.3
Angular: 2.4.10

**Comment by yuanqing** [comment]
Should your import call be `import autosizeInput from 'autosize-input'` instead?

Doing `const autosizeInput = require('autosize-input')` also works for me.
