### ISSUE TITLE
Doesn’t support font weight or font style

### ISSUE THREAD

**Issue by drwpow** [yuanqing/autosize-input#5]
**Problem:** Autosize doesn’t calculate width properly when using a `font-weight` other than `400` or a `font-style` other than `normal`.

**Reproduction:** http://jsfiddle.net/drewpowers/98k622ah/46/

**Suggestion:** Added a pull request with suggested changes here: https://github.com/yuanqing/autosize-input/pull/4

**Comment by antonlvovych** [comment]
+1 for this problem.

Don't forget about `letter-spacing` property which causes the same bug.

**Comment by twolfson** [comment]
I believe this has been resolved now that #4 was landed
